AnacondaRecipes/numpy-feedstock

- recipe/0005-intel-init-mkl.patch
- recipe/meta.yaml
When using `mkl_rt` (single dynamic library linkage), NumPy should use Intel(R) MKL only 
through LP64 interface, since NumPy's BLAS code is written with BLAS length parameters being
32-bit integers.
During the initialization, the threading layer is also initialized to alter MKL's
default choice.
If Gnu OpenMP library is detected as already loaded, the unset `MKL_THREADING_LAYER` is
interpreted as a liberal license to use Gnu OMP.
Vanilla Intel(R) MKL interprets that as use Intel(R) OpenMP*, resulting in erratic results
from MKL's threaded function called, like `sgemm`.
Example, demonstrating the issue that this patch fixes:
```
import numpy as np
import os.path
np.random.seed(666)
size = 1000
z = np.random.rand(size, size).astype('float32')
x = np.random.rand(size, …
```
> ENH: Adding dummy module `_mklinit` to initialized MKL RT

- recipe/0001-fix-windows-case-sensitivity.patch
- recipe/0002-simplify-arch-flags.patch
- recipe/0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
- recipe/0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
- recipe/0005-disable-broken-tests.patch
- recipe/0006-use-mklfft-when-available.patch
- recipe/0007-define-mkl_version-in-__init__.py.patch
- recipe/0008-intel-umath-optimizations.patch
- recipe/0009-intel-mkl_mem-all.patch
- recipe/0010-intel-init_mkl.patch
- recipe/0011-intel-mkl_random.patch
- recipe/0012-Remove-ICC-specific-flags.patch
- recipe/0013-Remove-np.invsqrt.patch
- recipe/0014-Rewrite-inlining.patch
- recipe/0015-Fixes-from-Intel-Distribution.patch
- recipe/meta.yaml
This updates the build to accommodate NumPy 1.16 and corresponding
performance patches from Intel.
Checklist
> Update to NumPy 1.16

- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/mkl_random_patches/0001-removing-gcc-pragma-windows.patch
In order to get downstream packages to build, some needed to be built against an older `numpy`. These are the changes I needed to make to get a `numpy-devel` built against MKL 2021. Some example downstream packages were `scipy` & `numexpr`.
> Updating recipe to support MKL 2021 rebuild.

- recipe/meta.yaml
Requirements:
- https://github.com/numpy/numpy/blob/v1.21.5/pyproject.toml
- https://github.com/numpy/numpy/blob/v1.21.5/tools/cythonize.py
- https://github.com/numpy/numpy/blob/v1.21.5/environment.yml
- https://github.com/numpy/numpy/blob/v1.21.5/setup.py
- https://github.com/numpy/numpy/blob/v1.21.5/test_requirements.txt
Actions:
1. Bump build number to `2`
2. Remove skipping `py2k`
3. Skip `py>311`, see https://github.com/numpy/numpy/blob/c3d0a09342c08c466984654bc4738af595fba896/setup.py#L409
4. Update host requirements: 
- add `packaging` for `osx-arm64,` see https://github.com/numpy/numpy/blob/c3d0a09342c08c466984654bc4738af595fba896/pyproject.toml#L4
- update pinning to `cython >=0.29.24`, see https://github.com/numpy/numpy/blob/c3d0a09342c08c466984654bc4738af595fba896/pyproject.toml …
> Rebuild numpy 1.21.5

- recipe/meta.yaml
Changelogs:
- https://github.com/numpy/numpy/blob/v1.22.3/doc/changelog/1.21.4-changelog.rst
- https://github.com/numpy/numpy/blob/v1.22.3/doc/changelog/1.22.0-changelog.rst
- https://github.com/numpy/numpy/blob/v1.22.3/doc/changelog/1.22.1-changelog.rst
- https://github.com/numpy/numpy/blob/v1.22.3/doc/changelog/1.22.2-changelog.rst
- https://github.com/numpy/numpy/blob/v1.22.3/doc/changelog/1.22.3-changelog.rst
Requirements:
- https://github.com/numpy/numpy/blob/v1.22.3/pyproject.toml
- https://github.com/numpy/numpy/blob/v1.22.3/tools/cythonize.py
- https://github.com/numpy/numpy/blob/v1.22.3/environment.yml
- https://github.com/numpy/numpy/blob/v1.22.3/setup.py
- https://github.com/numpy/numpy/blob/v1.22.3/test_requirements.txt
Actions:
1. Skip `py<38`
2. Remove skipping `py>311`, see …
> numpy 1.22.3

- recipe/conda_build_config.yaml
- recipe/meta.yaml
Rebuild numpy 1.21 after libgfortran update and openblas rebuild.
> Rebuild numpy 1.21

- recipe/0005-test-ctypeslib-py37.patch
- recipe/aarch_site.cfg
- recipe/conda_build_config.yaml
- recipe/install_base.sh
- recipe/meta.yaml
Rebuild numpy 1.19 after libgfortran update and openblas rebuild (against new libgfortran).
A number of changes were necessary:
* Worked around the build system trying to use the system gcc for linking.
* Worked around the build system setting the system root to '/' while linking.
* Marked additional tests to be skipped with comments.
* Override site.cfg on aarch64 (taken from numpy-feedstock master).
* Constrain setuptools version on Windows to fix an incompatibility.
Plus the usual little overrides.
> Numpy 1.19 b1

- recipe/0020-disable-test-nan-openblas.patch
- recipe/0021-disable-test-gcd-overflow-s390x.patch
- recipe/conda_build_config.yaml
- recipe/install_base.sh
- recipe/meta.yaml
- recipe/numpy_test.py
Rebuild numpy 1.16 after libgfortran update and openblas rebuild (against new libgfortran).
Only small changes were necessary.
> Numpy 1.16 b4

- recipe/conda_build_config.yaml
- recipe/meta.yaml
`numpy` version `1.23.3`
1. - [x] Check the upstream
https://github.com/numpy/numpy/tree/v1.23.3
2. - [x] Check the pinnings
3. - [x] Check the changelogs
https://github.com/numpy/numpy/tree/v1.23.3/doc/changelog
https://github.com/numpy/numpy/blob/main/doc/changelog/1.23.2-changelog.rst
https://github.com/numpy/numpy/blob/main/doc/changelog/1.23.3-changelog.rst
There are currently no mayor braking issues mentioned in the changelog. 
The changes mentioned were bug fixes or new features.
4. - [x] Additional research
https://github.com/conda-forge/numpy-feedstock/issues
There are some known issues mentioned on the upstream at the time of the review, however the issues mentioned do not seem to be breaking issues. 
5. - [x] Verify the `dev_url`
https://github.com/numpy/numpy
6. - [x] Verify …
> update `numpy` to version `1.23.3`

- recipe/meta.yaml
Minor version bump from 1.23.4 to 1.23.5
- updated version number
- updated SHA
> numpy version 1.23.5

- recipe/conda_build_config.yaml
- recipe/meta.yaml
**Jira ticket:** 
[PKG-40](https://anaconda.atlassian.net/browse/PKG-40)
The upstream data:
Anaconda recipe for 1.22: https://github.com/AnacondaRecipes/numpy-feedstock/tree/numpy122
conda_build_config.yaml:  https://github.com/AnacondaRecipes/numpy-feedstock/blob/numpy122/recipe/conda_build_config.yaml
Upstream repo for 1.22: https://github.com/numpy/numpy/tree/maintenance/1.22.x
**_Actions:_**
- bumped build number
- In order to build `ppc36le`, removed `8.2` pinnings from conda_build_config.yaml, and used the latest compiler versions.
> NumPy v1.22 for ppc64le py3.10

- recipe/conda_build_config.yaml
- recipe/meta.yaml
Changes:
1.23 built against mkl 2023
> Np124/mkl2023 - skip CI

- recipe/conda_build_config.yaml
- recipe/install_base.bat
- recipe/install_base.sh
- recipe/meta.yaml
Changes:
1.23 built against mkl 2023
> Np123/mkl2023 - skip CI

- recipe/conda_build_config.yaml
- recipe/install_base.bat
- recipe/install_base.sh
- recipe/meta.yaml
Changes:
1.22 built against mkl 2023
> Np122/mkl2023 - skip CI

- recipe/conda_build_config.yaml
- recipe/install_base.bat
- recipe/install_base.sh
- recipe/meta.yaml
Changes:
1.21 built against mkl 2023
set setuptools version, update pip flags
skip 2 tests failing with mkl 2023
> Np121/mkl2023 - skip CI

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Changes:
1.19 built against mkl 2023
skip 2 tests failing with mkl 2023
> Np119/mkl2023 - skip CI

- recipe/meta.yaml
- recipe/patches/0007-enable-meson-build.patch
Changes:
- Update to 1.25.0
- enable meson build for py>311
- clean test skip section
Release note: https://github.com/numpy/numpy/releases/tag/v1.25.0
https://github.com/numpy/numpy/tree/v1.25.0
https://github.com/numpy/numpy/blob/v1.25.0/pyproject.toml#L1
https://github.com/numpy/numpy/blob/v1.25.0/setup.py
https://github.com/numpy/numpy/blob/v1.25.0/test_requirements.txt
> PKG-2241 - numpy 1.25.0

- recipe/meta.yaml
Changes:
- comment out mkl_fft and mkl_random when py>=312 as these need numpy.disutils which is not available on 3.12.
- the build number is not incremented as the 3.12 build has not been published yet.
> ci skip comment out mkl_fft and mkl_random

- recipe/meta.yaml
numpy 1.26.3
- [PKG-3722](https://anaconda.atlassian.net/browse/PKG-3722)
- [Upstream repository](https://github.com/numpy/numpy/tree/v1.26.3)
- [Upstream changelog/diff](https://github.com/numpy/numpy/releases)
- Bump version to `1.26.3`
[PKG-3722]: https://anaconda.atlassian.net/browse/PKG-3722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 1.26.3

- recipe/meta.yaml
`numpy 1.21.6`
**Destination channel:** Defaults
- [PKG-4004](https://anaconda.atlassian.net/browse/PKG-4004) 
- [Upstream repository](https://github.com/numpy/numpy/tree/v1.21.6)
- [Upstream changelog/diff](https://github.com/numpy/numpy/releases/tag/v1.21.6)
- Skipped 2 failing tests:
- Slight error in linear interpolation precision on all platforms except Windows. Related upstream issue: https://github.com/numpy/numpy/issues/22073
- Bug with uint8 einsums on osx-64 using clang. Related upstream issue: https://github.com/numpy/numpy/issues/24732
[PKG-4004]: https://anaconda.atlassian.net/browse/PKG-4004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PKG-4004] 1.21.6

- abs.yaml
- recipe/meta.yaml
numpy 1.26.4
- [PKG-4012](https://anaconda.atlassian.net/browse/PKG-4012)
- [Upstream repository](https://github.com/numpy/numpy/tree/v1.26.4)
- [Upstream changelog/diff](https://github.com/numpy/numpy/releases)
- Update version and dependencies
- Add `abs.yaml` for 3.12 build
- Build for 3.12
[PKG-4012]: https://anaconda.atlassian.net/browse/PKG-4012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Version 1.26.4

- abs.yaml
- recipe/install_base.sh
- recipe/meta.yaml
- recipe/patches/0004-Partially-revert-function-blocklisting-for-glibc-lt-2.18.patch
Changes:
- Update to 2.0.0rc1
- rebase patches
- set destination channel as ad-testing/label/numpy2
Release note: https://github.com/numpy/numpy/releases/tag/v2.0.0rc1
https://github.com/numpy/numpy/tree/v2.0.0rc1
https://github.com/numpy/numpy/blob/v2.0.0rc1/pyproject.toml
https://github.com/numpy/numpy/blob/v2.0.0rc1/meson.build
https://github.com/numpy/numpy/blob/v2.0.0rc1/meson_options.txt
https://github.com/numpy/numpy/blob/v2.0.0rc1/test_requirements.txt
> update to 2.0.0rc1

- recipe/meta.yaml
For some reason, the previous build of 1.21.6 wasn't uploaded for win-64.
> Rebuild for win-64. 

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Package Name: NumPy
Version: 2.00
Destination Channel: defaults
Links:
•	JIRA Ticket:  https://anaconda.atlassian.net/browse/PKG-5130
•	[Upstream Repository](https://github.com/numpy/numpy)  
•	[Upstream Changelog/Diff](https://github.com/numpy/numpy/compare/v1.26.5...v2.0.0)
Explanation of Changes:
•	Updated the NumPy base package to version 2.00.
•	This update is to enable building the MKL packages and prepare for the full version of NumPy 2.00 at a later date.
**Following these instructions to remove errors seen in linux-64 and win-64:** https://github.com/AnacondaRecipes/numpy-feedstock/blob/b43b810ff6405cd8354e76d78ac2c463824a251b/recipe/meta.yaml#L58-L61
> 2.0.0 numpy-base main

- recipe/conda_build_config.yaml
- recipe/meta.yaml
[PKG-5130](https://anaconda.atlassian.net/browse/PKG-5130)
activate full build on CI (only have numpy-base 2.0.0 right now)
[PKG-5130]: https://anaconda.atlassian.net/browse/PKG-5130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Numpy 2.0.0 main

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/install_base.bat
- recipe/install_base.sh
- recipe/meta.yaml
numpy 2.0.2 b1
- [PKG-7065](https://anaconda.atlassian.net/browse/PKG-7065)
- [Upstream repository](https://github.com/numpy/numpy/tree/v2.0.2)
- Relevant dependency PRs:
- AnacondaRecipes/intel_repack-feedstock#26
- AnacondaRecipes/mkl-service-feedstock#6
- Bumped `mkl` version
- Made linter happy
- Added `run_constrained` to `numpy-base` so CI tests pass when not building/testing `numpy`
[PKG-7065]: https://anaconda.atlassian.net/browse/PKG-7065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rebuild 2.0.2 with mkl v2025

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/install_base.bat
- recipe/install_base.sh
- recipe/meta.yaml
numpy 2.1.3 b1
- [PKG-7064](https://anaconda.atlassian.net/browse/PKG-7064)
- [Upstream repository](https://github.com/numpy/numpy/tree/v2.1.3)
- Relevant dependency PRs:
- AnacondaRecipes/intel_repack-feedstock#26
- AnacondaRecipes/mkl-service-feedstock#6
- Bumped `mkl` version
- Made linter happy
[PKG-7064]: https://anaconda.atlassian.net/browse/PKG-7064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rebuild 2.1.3 with mkl v2025

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
numpy 1.25.2
- [PKG-7067](https://anaconda.atlassian.net/browse/PKG-7067) 
- [Upstream repository](https://github.com/numpy/numpy)
- Ensured compatibility with MKL 2025
[PKG-7067]: https://anaconda.atlassian.net/browse/PKG-7067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> numpy 1.25.2 rebuild against mkl 2025

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
numpy 1.26.4
- [PKG-7066](https://anaconda.atlassian.net/browse/PKG-7066) 
- [Upstream repository](https://github.com/numpy/numpy)
- Ensured compatibility with MKL 2025
[PKG-7066]: https://anaconda.atlassian.net/browse/PKG-7066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> numpy 1.26.4 rebuild against mkl 2025

- abs.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
numpy 2.2.5
- [PKG-XXXX](https://anaconda.atlassian.net/browse/PKG-XXXX) 
- [Upstream repository](https://github.com/numpy/numpy)
- Ensured compatibility with MKL 2025
> numpy 2.2.5 rebuild against mkl 2025
